name: timewaretest1
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  http: ^0.13.5
  table_calendar: ^3.0.7
  flutter_bloc: ^8.1.1
  provider: ^6.0.4
  equatable: ^2.0.5
  intl: ^0.17.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
